# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Progress/Vivado/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/Progress/Vivado/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Progress/Vivado/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/define.vh
read_verilog -library xil_defaultlib {
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/alu.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/branch_judge.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/control.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/data_memory.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/datapath.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/ex_mem_regs.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/ex_stage.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/forward_unit.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/id_ex_regs.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/id_stage.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/if_id_regs.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/if_stage.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/instr_decode.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/instr_memory.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/mem_stage.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/mem_wb_regs.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/mux.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/mux3_1.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/pc_reg.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/register.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/riscv.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/wb_stage.v
  D:/Progress/Vivado/project_1/project_1.srcs/sources_1/new/riscv_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top riscv_top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_top_utilization_synth.rpt -pb riscv_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
